name: Build and Test with Maven

on:
  push:
    branches:
      - develop  # Esto se dispara cuando haces push a la rama develop
  pull_request:
    branches:
      - develop  # También cuando abres un PR hacia develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 21 (Adoptium)
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'  # Cambiado a 'temurin' (Adoptium)
    
    - name: Build with Maven
      run: mvn clean install  
    
    - name: Run tests
      run: mvn test
